  # version: '3.8'

  services:
    postgres:
      image: bitnami/postgresql:latest 
      ports:
        - '5433:5432'
      environment:
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=docker
        - POSTGRES_DB=matriculadb
      volumes:
        - matriculadb_pg_data:/bitnami/postgresql

  volumes:
    matriculadb_pg_data: